# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2.1
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
- gem install xcpretty -N --no-ri --no-rdoc
script:
#- set -o pipefail \
  #xcodebuild build-for-testing -workspace Example/SimpleRecorder.xcworkspace -scheme SimpleRecorder-Example -destination 'platform=iOS Simulator,name=iPhone 6' \
  #xctool -workspace Example/SimpleRecorder.xcworkspace -scheme SimpleRecorder-Example run-tests -test-sdk iphonesimulator9.3 \
  
  #xcodebuild clean test -workspace Example/SimpleRecorder.xcworkspace -scheme SimpleRecorder-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' -enableCodeCoverage YES | xcpretty
- set -o pipefail
- xcodebuild clean test -workspace Example/SimpleRecorder.xcworkspace -scheme SimpleRecorder-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' | xcpretty
- pod lib lint
